init_config:
instances:
  - dbm: true
    host: 'mssql'
    port: 1433
    username: datadog
    password: 'Password123!'
    connector: odbc
    driver: "ODBC Driver 18 for SQL Server"
    connection_string: "TrustServerCertificate=yes;"
    query_activity:
      collection_interval: 0.01
    tags:  
      - 'service:dotnet-dbm'
      - 'env:dev'
